name: On Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  check-format-test:
    uses: ./.github/workflows/check-format-test.yml
    with:
      is-release: true
    secrets: inherit

  build-publish:
    needs: check-format-test
    uses: ./.github/workflows/build-publish.yml
    with:
      is-release: true
    secrets: inherit
